import type { Metadata } from "next";
import "@/app/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import StyledComponentsRegistry from "@/lib/antd.registry";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider>
          <StyledComponentsRegistry>
            <AntdRegistry>{children}</AntdRegistry>
          </StyledComponentsRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
