import type { Metadata } from "next";
<<<<<<< HEAD
import "@/app/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import StyledComponentsRegistry from "@/lib/antd.registry";
import { ConfigProvider } from "antd";
=======
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ["latin"] });
>>>>>>> d789e8c1d8be88e18e1b9750024b58318f69242f

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        <ConfigProvider>
          <StyledComponentsRegistry>
            <AntdRegistry>{children}</AntdRegistry>
          </StyledComponentsRegistry>
        </ConfigProvider>
=======
      <body className={inter.className}>
        <AntdRegistry>
          {children}
        </AntdRegistry>
>>>>>>> d789e8c1d8be88e18e1b9750024b58318f69242f
      </body>
    </html>
  );
}
